### ISSUE TITLE
Add better API's for ETFs

### ISSUE THREAD

**Issue by PhKP** [buchen/portfolio#1383]
Hi

Thank you for creating this amazing program.

I am experiencing very bad quality of historical data on ETF's when getting this trough Yahoo.

I propose to create a way to get data directly through API's like this:
https://console.developer.deutsche-boerse.com/apis/xetra-public-data-set/1.0.0

Please use QDVE.DE with ISIN: IE00B4L5Y983 as test.

Each user of the program could put in their own API key when setting up the Security.

Best Regards Philip

**Comment by buchen** [comment]
Hi Philip,

configuring API keys is not a problem, that is done for other providers already (AlphaVantage, Quandl, soon Finnhub).

I had a look at the API with
https://api.developer.deutsche-boerse.com/prod/xetra-public-data-set/1.0.0/xetra?isin=IE00B4L5Y983&date=2020-02-14&offset=0&limit=500

It is data *per day* aggregated to the minute. As PP needs the "closing" quote, I'd have to do at least one call per day and take the last trade. "at least one call per day" because there is a limit of maximum 1000 trades in the response. Is this what you are suggesting to do?

The rate limit with *100 calls per second* looks generous.

BTW, this is what I found as documentation: https://github.com/Deutsche-Boerse/dbg-pds/blob/master/API_README.md#get-1

Do you know that you can also grab historical quotes from a web page? That might also be a good source for ETF data.

Andreas.

**Comment by PhKP** [comment]
Hi Andreas

No not exactly, that process sounds a bit too heavy. I thought that the API might be able to supply the historical data in a more intelligent way. I didn't look into exactly how.

Börse Frankfurt have [this](https://www.boerse-frankfurt.de/etf/ishares-s-p-500-information-technology-sector-ucits-etf-usd-acc) table which shows the data that we need. My guess would be that we could get the same data from the API. But i might be mistaken.. Otherwise the heavy process might be the only way..

Yes I know that the historical data can be gathered from a web page but it doesn't work for me with the above website from Börse Frankfurt.

Best regards Philip

**Comment by buchen** [comment]
> Yes I know that the historical data can be gathered from a web page but it doesn't work for me with the above website from Börse Frankfurt.

It does not work because the table is dynamically loaded via JavaScript.

The source URL seems to be: https://api.boerse-frankfurt.de/data/price_history?limit=50&offset=0&isin=IE00B3WJKG14&mic=XETR&minDate=2019-02-15&maxDate=2020-02-15

I could not find anything on the site forbidding the automatic download. I'll check some more, because that endpoint could work.

> No not exactly, that process sounds a bit too heavy. I thought that the API might be able to supply the historical data in a more intelligent way. I didn't look into exactly how.

I could not find one. But it does not mean there is none. The documentation has ... room for improvement.

**Comment by PhKP** [comment]
> The source URL seems to be: https://api.boerse-frankfurt.de/data/price_history?limit=50&offset=0&isin=IE00B3WJKG14&mic=XETR&minDate=2019-02-15&maxDate=2020-02-15
> 
> I could not find anything on the site forbidding the automatic download. I'll check some more, because that endpoint could work.

Interesting. I hope that is our solution.

**Comment by buchen** [comment]
With the next version PP can extract quotes from arbitrary JSON feeds by providing JSONPath expressions for date and close.

<img width="519" alt="Bildschirmfoto 2020-02-17 um 18 49 15" src="https://user-images.githubusercontent.com/587976/74676387-36973b80-51b6-11ea-9bd4-7ce2d7fbb3d8.png">

**Comment by PhKP** [comment]
https://media.giphy.com/media/5FoxedYWNVmO4/giphy.gif

**Comment by Flippo24** [comment]
Nice to read you are working with the api from Börse Frankfurt.
Today i wrote a provider for it. 

![grafik](https://user-images.githubusercontent.com/5230426/74781120-34f67200-52a1-11ea-9525-1b571084694e.png)

![grafik](https://user-images.githubusercontent.com/5230426/74781218-61aa8980-52a1-11ea-9c39-7ce59aad0d3f.png)

It only works in editing view not in automatic updating.  The reason is, that the selection for "Börsenplatz" is saved as TickerSymbol. So the right original symbol QDVE will be replaced with the sybol the provider used for calling data. 

right:
![grafik](https://user-images.githubusercontent.com/5230426/74781780-763b5180-52a2-11ea-9e19-024723be03af.png)
wrong:
![grafik](https://user-images.githubusercontent.com/5230426/74781824-8ce1a880-52a2-11ea-8ed7-a29810746d01.png)

There is a need for a "providersymbol" in Security Attributes, which can be replaced by the provider selection.

**Comment by Flippo24** [comment]
#1387

**Comment by PhKP** [comment]
A very nice feature you added. Here is a difference with what I had with the Yahoo data and what I can extract from a Json API using the new feature.

Before:
<img width="1075" alt="Yahoo" src="https://user-images.githubusercontent.com/11960377/76709988-cb348100-6703-11ea-8b16-c6358b6267da.png">

After:
<img width="1070" alt="Json" src="https://user-images.githubusercontent.com/11960377/76709990-d25b8f00-6703-11ea-8da1-6f2aec31c873.png">

Thanks again :)

I will close the issue.
