### ISSUE TITLE
Translation instructions

### ISSUE THREAD

**Issue by iwalucas** [buchen/portfolio#1455]
Hello, I would like to translate this tool to Portuguese Brazil, do you have instructions to do it?
I saw that there is a file in the format `messages_[LANG].properties`, should I just do a PR with the file containing the translation `messages_pt.properties`?
Thanks

**Comment by Ragas13** [comment]
@iwalucas 

Regarding new translation properties, you could review below commits to estimate the necessary changes:

* https://github.com/buchen/portfolio/commit/96cdfb697b067e72326d130d544d812b97903abf
* https://github.com/buchen/portfolio/commit/fbda68837aa1dd9df50be18124fb533f6d7d4a7c
* https://github.com/buchen/portfolio/commit/3f3bc7762bdc572579ad8674268914b2a00e5a10

**Comment by iwalucas** [comment]
@Ragas13 
thanks! I will start it and do a PR once I am done...

**Comment by buchen** [comment]
Hi @iwalucas,

there are two ways: one is to update the message files, create a PR. That is probably the easiest if you know the tools. Inside Eclipse, I am using the [ResourceEditor](https://marketplace.eclipse.org/content/resourcebundle-editor#group-details) plugin (this plugin formats the resource files) - do not worry for the formatting to much, we can do this as well.

Alternatively, you could also join on POEditor https://poeditor.com/join/project/4lYKLpEWOY and translate strings there. I am not so sure, however, if that makes sense for the initial bulk translation.

**Comment by iwalucas** [comment]
Hi @buchen, thanks. I have forked and was already working on the bundles file, but am also on POEditor, so I requested access there... I will try directly on POEditor, but if that doesnt work, I will fallback to the file directly for the initial one.

**Comment by buchen** [comment]
Hi @iwalucas,

two questions:

First: I have tested downloading the translations from POEditor and that looks good. Great! I will commit the labels to the repository later today or tomorrow. Do you want me to build a test version that you can use? If so, which binary (win, macOS, Linux)?

Second: How different is Portuguese from Portuguese (Brazil)? I am asking because if we commit it as country variant only, it would mean that Portuguese users would see the English version. And only if your locale is correctly configured with language and country would the translations show up. (I also have to work on the language selector to support not only language but also country)

**Comment by iwalucas** [comment]
Hi @buchen,

I am glad it worked! I was afraid that for some reason it would not :)

If you can compile a MacOS would be great! I will keep working on the translation today.

Brazilian Portuguese is somewhat different from the Portugal one, but I would say that its not that different, and I am pretty sure very little would change. Its just some words that change, the structure and everything else is the same. 

Honestly I am not sure which works best, but I would guess that bringing the Portuguese (BR) version would be fine.

Thanks!

**Comment by iwalucas** [comment]
@buchen I have finished the translation! A few fuzzy ones that I want to check on the application, so if you can compile it and send me, I will be able to review it.

Thanks!

**Comment by buchen** [comment]
I have uploaded a release: https://www.dropbox.com/s/d1uw3yfgrbvcjy9/PortfolioPerformance-distro-0.45.2-SNAPSHOT-macosx.cocoa.x86_64.zip?dl=0  (might take some time as my Internet connectivity seems to be very slow at the moment)

**Comment by buchen** [comment]
I have just updated the download above again

**Comment by iwalucas** [comment]
@buchen thanks, I have fixed a few translations terminologies, and also one that made the system crash b/c I had a space `{1 }`... (TooltipMaxDrawdownDurationFromXtoY).... 
Probably b/c of this error the Performance dashboard didnt get translated...

also, I added a line break to ColumnLatestPrice and ColumnLatestTrade, since it was overlapping the value... not sure if that will automatically adjust or overlap the inferior border....

apart from that, the translation looks amazing! I am very happy with the result.... if you can generate a new binary, I will test it out. thanks!

**Comment by buchen** [comment]
Here another build: https://www.dropbox.com/s/kirx4rleu51vr1d/PortfolioPerformance-0.45.2-SNAPSHOT.dmg?dl=0 It really looks amazing! 

>  I added a line break to ColumnLatestPrice and ColumnLatestTrade

The labels cannot really handle line breaks - see the screenshots. I think I have to redo the UI code so that they are not overlapping (and simply cut off if the windows is too small).

<img width="136" alt="Bildschirmfoto 2020-03-22 um 08 04 32" src="https://user-images.githubusercontent.com/587976/77244672-e88fb080-6c17-11ea-81ef-7028444f2a50.png">

<img width="283" alt="Bildschirmfoto 2020-03-22 um 08 06 45" src="https://user-images.githubusercontent.com/587976/77244673-e9c0dd80-6c17-11ea-9140-31fac9628332.png">

One more question about the **format for dates**: I am using the standard Java format for a "medium" long date format. In German, this is "22.03.2020" (22 March 2020). As you can see from the screenshot, Java formats it quite different in Portuguese.

<img width="299" alt="Bildschirmfoto 2020-03-22 um 08 10 04" src="https://user-images.githubusercontent.com/587976/77244689-2ee50f80-6c18-11ea-802d-b5c2a1a6e96c.png">

I could change it to a shorter format - just for Portuguese. Does this look better?
<img width="244" alt="Bildschirmfoto 2020-03-22 um 08 39 32" src="https://user-images.githubusercontent.com/587976/77244706-ac108480-6c18-11ea-899a-67bf1f226515.png">

**Comment by iwalucas** [comment]
Yes, the shorter format looks better!

I will try the new binary shortly and will let you know if I see any more changes.
Thanks

**Comment by iwalucas** [comment]
Thats looking great... I change one translation only `LabelSecurityPerformance` to make it clearer, but think we are good now :)

**Comment by buchen** [comment]
I plan to publish a new version today or tomorrow.
