### ISSUE TITLE
Increase shares display precision

### ISSUE THREAD

**Issue by adrienkohlbecker** [buchen/portfolio#1459]
Hello!

First of all thanks for this awesome tool which I've just started using.

Most of my transactions have partial shares with 5 numbers of precision, however in the UI everything is displayed with 3 numbers. That makes my transactions harder to reconcile and navigate, and my account statements less useful, as I have to hover around each number. Could this be increased? Or made configurable?

<img width="152" alt="Screenshot 2020-03-22 at 12 31 23" src="https://user-images.githubusercontent.com/70469/77248351-0d485000-6c39-11ea-925d-08dafcdd2aad.png">

Thanks :-)

**Comment by Pnda87** [comment]
+1 for making the number of digits to display configurable. 
others already wished to display only integer shares..

(if I find some time, I'll try to implement this)

**Comment by metal450** [comment]
Agree, the very low precision makes it really hard to use for bitcoin

**Comment by metal450** [comment]
Also related to precision: it would be nice to have more digits for quotes as well - some microtransaction cryptos have values that are less than the precision allowed by this software (for instance, KIN has a value of 0.0000126USD, which PortfolioPerformance only rounds to "zero," thus it shows all my holdings for that crypto as 100% loss - value of $0).

**Comment by buchen** [comment]
> some microtransaction cryptos have values that are less than the precision allowed by this software (for instance, KIN has a value of 0.0000126USD, which PortfolioPerformance only rounds to "zero," thus it shows all my holdings for that crypto as 100% loss - value of $0).

for reasons of simplicity, I decided to *display* a maximum of three digits in the UI. My basic assumption was: mostly one will have "whole pieces". Because I want to align on the decimal point, there would be a lot of empty space on every line. I think this is what we can make configurable. Internally, PP is calculating with 6 digits for shares.

PP is storing money values with 2 digits. That is not trivial to change because a) PP is currently storing cent values and is working with longs (no fractions) and b) one would have to come up with different rounding strategies (obviously one cannot have fractions of a cent on an cash account). This is not trivial to change. Maybe the valuation of a line item in the statement of assets can have more digits - not sure.

**Comment by metal450** [comment]
> for reasons of simplicity, I decided to _display_ a maximum of three digits in the UI. 

Yup, I saw that you can reveal all 6 places by hovering with the mouse.  It does becomes quite cumbersome though if you have many different cryptos in your portfolio, as you need to hover them one at a time (i.e. cannot see all values simultaneously).  In the case of "high-value" cryptos like bitcoin, those decimals can actually make a noticeable difference in terms of holdings.  Making it configurable would certainly be very welcome (personally I'd always show all 6 places - ideally would be 8, as that's the bitcoin precision, but at least showing the 6 that are currently available would be a significant usability improvement)

> PP is storing money values with 2 digits.

I'm actually getting 4 digits of precision for quotes.  i.e. $VET has an accurate quote of .0182.  It's just tokens that are valued at less than .0001 where it doesn't work, since they get rounded to zero.

**Comment by buchen** [comment]
> I'm actually getting 4 digits of precision for quotes

Yes. Quotes = 4 digits, money = 2 digits

**Comment by metal450** [comment]
So the 2nd issue I'm describing here is with the precision of quotes (rather than money): for tokens that have very small values that aren't representable in 4 digits, the quote gets rounded to zero, & thus no matter how many you own it can only show 0 value.  For instance, if you own 12 million Kin, it has value of $150.  But since the unit value (aka quote) is < 4 digits, it's not possible to represent.  Does that make sense?  The issue is the quotes rather than the money.

**Comment by metal450** [comment]
Since it looks like the 'display precision' issue was resolved (thanks for the setting!) and I sort of hijacked this original thread for what ended up being a separate issue, I'll spin off the quote precision issue into a new issue, for clarity.  I think this one can be closed :)
