### ISSUE TITLE
0.46.1: Creating a new classification in Taxonomy not saved when moved to first-level

### ISSUE THREAD

**Issue by ronnykrijt** [buchen/portfolio#1520]
When a classification is created, it creates under the active node. Dragging/dropping allows moving elsewhere. When moving to the highest level (making multiple entries at the highest level), it is dragged there. Multiple changes are then possible. WHen leaving and re-entering the taxonomy then is reset to only one entry at the highest level, making all changes made after the drag/drop gone.

**Comment by Ragas13** [comment]
At the of a pyramid hierarchy is only one item possible. It's a drag and drop behaviour but it works as intended.

**Comment by ronnykrijt** [comment]
OK, good to know, as I thought that the top would be the overall of the taxonomy itself (consider the taxonomy infull the highest, wasnt aware 1 has to be the overall). It is a pity though, that it doesn't error or whatsoever, as now you loose work, without knowing it.

**Comment by buchen** [comment]
Okay, I fixed the problem that one could drag an element to the top-level.

Logically, I have to top-level node so that one can see how many assets are considered for rebalancing. For example, if you would want to rebalance only some categories, just do not categorize the other assets. The totals in "actual assets" etc. are relevant.
