### ISSUE TITLE
auto update doesn't work on 0.49.3 Big Sur

### ISSUE THREAD

**Issue by cqst** [buchen/portfolio#1873]
Hi

wanted yo upgrade to 0.49.4 (manually from the menu check for updates) on mba M1 bigsur 11.1 but I got this error : 

<img width="766" alt="Capture d’écran 2020-12-16 à 15 49 17" src="https://user-images.githubusercontent.com/4339847/102363994-4a6a2480-3fb6-11eb-99be-534f47c3f689.png">

Basically it says dependency conflict 

Regards

**Comment by buchen** [comment]
Yes. I noticed too. The upgrade does not work.

That's why I build a message saying "For now, on Big Sur please re-download PP". But this message does not come up because of this error.

So, Please, download the version from here:
https://github.com/buchen/portfolio/releases/download/0.49.4/PortfolioPerformance-0.49.4.bigsur.dmg

(Open DMG, move to application folder).

Hopefully the next online update will work - I am working on it.

**Comment by pat-s** [comment]
I think this issue could be unpinned :)
