### ISSUE TITLE
CSV import: Auto detect delimiter (or ability to load a saved config as default)

### ISSUE THREAD

**Issue by RoChess** [buchen/portfolio#1881]
I'm forced to constantly change settings to work in a US/English environment.

Since the entire content of the CSV file is shown, and there was absolutely no ";" character used, would it be possible to auto-detect the delimiter? On the small import file I was using there were zero semi-colons, but 602 commas.

Ideally Portfolio Performance has a locale setting (or detects it from the OS), because that would solve date format, and number format as well. In the US they use MM/DD/YYYY, and #,##0.00 format, but within Windows this can be obtained via API so it would work for any user preference.

I've saved a "Fidelity" configuration after getting it all sorted, but there is no way to get that loaded as the "default" withing Portfolio Performance, because that would also be a workable solution.

**Comment by buchen** [comment]
I read a couple of suggestions here:
* Determine the separator based on the locale
* Determine the separator based based on the content of the first couple of lines because the content will most likely have more than one column
* Preset the date format based on the column
All valid suggestions. Let me have a look.


For the configuration: If you save the configuration (the little cog button within the Import dialog), then you should be able to open a file and directly apply the configuration: Use *File -> Import -> Template -> Fidelity (or whatever name you have given)*

<img width="926" alt="Bildschirmfoto 2020-12-19 um 12 16 17" src="https://user-images.githubusercontent.com/587976/102688007-01071880-41f4-11eb-8aaa-2c41ea1ea00c.png">

**Comment by RoChess** [comment]
Not sure if re-opening this closed ticket is the best way to do this, but here goes.

Now that I'm updated to a version that included this fix, I happened to require adding a 3rd securities account which is a 2nd Fidelity account, and instead of using my "Fidelity" saved config, tried to do a fresh import to test fix and discovered the following:

Mapping 'Value' worked perfect, and it automatically picked the correct 0,000.00 syntax.
Mapping 'Date' ended up picking YYYY/MM/DD, so I was still forced to correct this to MM/DD/YYYY.

Trimming of spaces also worked nicely, but that relates to another ticket.

PS: First created this 3rd new "Deposit Accounts", and then created a 3rd new "Securities Accounts" and used the drop down box to link it to the newly created "Deposit Accounts", but I did not "Save" this. Went back to the "Deposit Accounts" overview and imported the new CSV via right clicked on the 3rd newly created entry. During import on the 2nd screen I had to fix the securities accounts assignment. Since I skipped 'Save' this might be expected behavior, but within the session it was assigned correct inside "Securities Accounts" overview, so not sure if this is a tiny 'bug' or designed that way.
