### ISSUE TITLE
Performance calculation and trades mismatch

### ISSUE THREAD

**Issue by robertmarsal** [buchen/portfolio#1892]
**Describe the bug**
For a series of trades I had in my portfolio it looks like the calculations in the "Performance" > "Calculation" section differ from the values in the "Trades" section (added up).

In my case the value is 117.91 in the Performance calculation section and 117.89 when added up in the trades section

**To Reproduce**
I have uploaded a sample XML file to reproduce the issue here: https://gist.github.com/robertmarsal/47e3a12c99955b96b4732d5f005bee62

**Expected behavior**
Both values should be matching as there are no fees or anything extra to justify the difference.

**Screenshots**
![performance](https://user-images.githubusercontent.com/507871/102695063-fc0a8f00-421c-11eb-8f0d-373f4da51dd1.png)
![trades](https://user-images.githubusercontent.com/507871/102695068-fdd45280-421c-11eb-8ad2-de599833f2b4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.49.4

**Comment by inv-trad** [comment]
To be honest, this is most likely a rounding issue and not a bug.

The transactions are done in USD, the account is in GBP. I didn't go through the bookings to verify, but the Performance Calculation number is rounded just once (in the end) while each of the three trades in the Trades view is rounded. Summing up the rounded numbers gives that deviation. 

If you wanted to check yourself, you could create a spreadsheet with your bookings and silmulate the two results. In case that really produces a difference, we have a bug here otherwise it is just the result of rounding.

**Comment by robertmarsal** [comment]
Thank you for having a look @inv-trad. I agree that it must be a rounding issue somewhere but I am not too familiar with the code base yet to be able to make a suggestion where.

When I do the calculations manually the value I get is 117.89 which is the same as when adding up the Trades section Profit/Loss columns so that should be the correct value in my books. 

I'm happy to keep an eye on this and if I notice a difference that can't be justified by rounding open this issue again. 

Thanks again,
Rob
