### ISSUE TITLE
Statement of Assets purchase price value wrong

### ISSUE THREAD

**Issue by bobcho** [buchen/portfolio#1910]
Hi,

I have two securities accounts and used to trade this stock on both, but currently I have open position on just one of them. However, in "Statement of Assets" default view, the "Purchase price" for this particular stock is wrong when viewing entire portfolio (no filter).

Purchase price when filtered by 1st security account (the one with open position) is 35.66, then if I filter by the second security account the stock is not shown (correct,  there are no open positions there), and then when viewing "entire portfolio" the price seems to reflect old (closed) position on the second security account, thus incorrectly showing Purchase price of 45.75 (correct price is 35.66 as per the only security account that I'm trading this stock on).

I hope that I managed to explain the steps to reproduce.

**Comment by inv-trad** [comment]
I think, this is due to fifo at this point currently is not portfolio dependend. It's not trivial to fix this.

Could you please verify, if your issue is similar to the one described in this forum discussion.

https://forum.portfolio-performance.info/t/einstandskurs-und-preis-in-der-vermoegensaufstellung-bei-einem-wertpapier-in-zwei-depots-nicht-korrekt/12042

**Comment by bobcho** [comment]
Yes for what I understand from the google translation of the thread, it seems to be the same issue.

**Comment by inv-trad** [comment]
In that case, it looks like a solution will be there soon: https://github.com/buchen/portfolio/pull/1909
