### ISSUE TITLE
use BigDecimal instead of floating

### ISSUE THREAD

**Issue by Xyz00777** [buchen/portfolio#1972]
**Is your feature request related to a problem? Please describe.**
atm (when i understood it correct) we're using float for saving the values, but float is limited to 32bits and is not recommended for saving monetary values in float, int, doubles... because its limited and not accurate enough.

**Describe the solution you'd like**
BigDecimal can save a nearly unlimited amount of value in front and behind the "," and is more accuracy.
Somebody explained here fantastic why to use BigDecimal instead of float,double...
https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio 

**Improvement for PP**
we could save bigger values, it is more accurate, we could save cryptocurrency without the problem of not running out of space and getting negative numbers....

**Comment by Xyz00777** [comment]
i know that it will propably a huge amount of stuth who need to be changed in the code but with that change we dont have to think of stuff like "is the value probably to big and because of that we cant use it?"
the last days i saw many posts here and in the forum about features where we can't implement (like cryptocurrency with big values or brokers who give users money like 0,0000001€ or something like that who wee cant display at the moment) and are open to get worked on them but which cannot be started because the program does not support them at the moment

**Comment by chirlu** [comment]
Your understanding is wrong; PP doesn’t use floating-point numbers, much less 32-bit floating-point numbers. It uses 64-bit fixed-point arithmetic, i.e. it counts *integer* numbers of cents, of hundredth millionths of shared etc. There are no accuracy/rounding issues involved.

The reason for not using BigDecimal is performance (see the explanation in #1932).

**Comment by Xyz00777** [comment]
Did I understand it correct that he is already in the implementation of something like a mix of BigDecimal and long?
im l a little bit confused

**Comment by buchen** [comment]
> Did I understand it correct that he is already in the implementation of something like a mix of BigDecimal and long?

Yes. Most values at most of the time are ```long```. Think of it working with cents. Actually, I am storing the value as ```long``` and keep some kind of "default" precision if you look at the ```Values``` class.

However, some calculations involve amounts (2 digits precision) and security prices (now 8 digits) and shares (also 8 digits now). To not overflow the calcuation, I am using ```BigDecimal``` to do this calculations. Since most calculations, however, add or subtract the same type (e.g. summing up the total shares held), it is faster to do this in ```long```. My (layman) performance tests showed a significant increase when I converted shares into ```BigDecimal```.
