### ISSUE TITLE
Internal Rate of Return (IRR) - Decimal Places & Calculation Issue

### ISSUE THREAD

**Issue by the-please-is-mine** [buchen/portfolio#2391]
**Describe the bug**
I'm seeing a strange behaviour at one of my securities when it comes to the IRR (IZF). Normally I only see two decimal places but in one case it is a lot more (see screenshot). I did not change the default value for decimal places.

I also noticed that in the view "Wertpapiere" the value for IRR is different than in the detail view at the bottom. Maybe there is some sort of different calculation going on? I'm unsure about that and maybe someone with more knowledge could have a look at it.

**To Reproduce**
Can't really tell how to reproduce this other than giving out the exact details of my order? 

**Expected behavior**

1. I would expect to also have two decimal places at max.
2. I would expect that the two values are identical.

**Screenshots**
<img width="1552" alt="PP_Bug_IRR" src="https://user-images.githubusercontent.com/89104892/129796795-1d2d4bc8-ba7a-499c-aa7b-483ba3296032.png">

**Desktop:**

- OS: Big Sur 11.5.2
- Version 0.54.3 (Aug. 2021)

**Comment by chirlu** [comment]
I don’t see anything obviously wrong here; without the actual transactions, it’s impossible to check further. I don’t count more than two decimal places, either (,50: 5 – first place, 0 – second place).

If there is something you don’t understand, it’s better to ask on the forums instead of reporting a bug that probably isn’t.
