### ISSUE TITLE
Logos are cut off when displayed in the second or following column of a table

### ISSUE THREAD

**Issue by tquellenberg** [buchen/portfolio#2751]
**Describe the bug**
Logos are cut off by one pixel when displayed in the second or following columns of a table. (OS: Windows only.)
See https://forum.portfolio-performance.info/t/logos-werden-links-abgeschnitten/10294/11

**Fix**
On Windows systems the images are extended by one transparent pixel.

**Comment by CanePlayz** [comment]
@tquellenberg I'm still seeing this issue here:

![image](https://github.com/user-attachments/assets/862910cd-f782-4519-a8d5-ccfbadca3fc6)

**Comment by CanePlayz** [comment]
@buchen Might want to re-open this issue

**Comment by mierin12** [comment]
@CanePlayz I confirm that also have the cut off bug on Windows, light mode. 
But on dark theme, no, all is fine. 
I think the fix was reversed here https://github.com/portfolio-performance/portfolio/pull/3615 and here https://github.com/portfolio-performance/portfolio/pull/3643.
However, it seems that the fix itself was not perfect, as the logo were then cut off on the right side instead of the left side : https://forum.portfolio-performance.info/t/logos-werden-links-abgeschnitten/10294/13
