### ISSUE TITLE
Add logo.svg to the repository

### ISSUE THREAD

**Issue by whnr** [buchen/portfolio#3116]
Could you please add the `logo.svg` to the repository? Currently the [arch AUR package](https://aur.archlinux.org/packages/portfolio-performance-bin) is extracting it from the [website logo](https://www.portfolio-performance.info/images/logo.svg
). Linking to the repo would be a bit more robust.

**Comment by buchen** [comment]
Yes, will do.

(And as you noticed, I updated the logo on the web page, but not yet in the released binary).

**Comment by buchen** [comment]
done.

https://github.com/buchen/portfolio/blob/master/portfolio-product/icons/logo.svg

**Comment by buchen** [comment]
H @whnr - as I am not able to post a comment on the AUR package site (and I am not able to register because I cannot run the pacman command on my Mac), let me ask here:
* First, there seem to be two packages of PP: https://aur.archlinux.org/packages/portfolio-performance-bin and https://aur.archlinux.org/packages/portfolio - is this just coincidence, or is there a meaningful difference?
* Second, with one of the next updates, PP will require Java 17. How do I best tell?

**Comment by whnr** [comment]
Quoting the wiki:
> AUR packages are user-produced content. These PKGBUILDs are completely unofficial and have not been thoroughly vetted.

To your points.

there are usually three postfixes on AUR packages:
1. ` ` will be building from the last releases source
2. `-bin` builds based on the last released binary = no build needed
3. `-git` builds from the stable branch head

That’s why there are two packages. Your binaries work well, that’s why I use that package.

About Java updates: That’s one of the nice things I like about the AUR: I usually get your release update from GitHub and sometimes the same day someone will mark the package out of date.

At some point one of the packagers will repackage and check if everything works on a fully updated Arch system. This package has `jre-openjdk` as a dependency which is already at Java 19. Should something break, someone will comment on the AUR. I really like the very efficient community there.
