### ISSUE TITLE
Annuallisierter TTWROR (Performance Übersicht / Vermögensaufstellung)

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#427]
> PS: Ebenfalls könnte man zusätzlich auch den TTWOR noch annualisiert [...](Period Return, Annualized Return)

**Comment by buchen** [comment]
@Beluk diesen Issue habe ich auf Grund von #427 angelegt

Ich habe ganz am Anfang von der Entwicklung von PP versucht den internen Zinsfuß für einen Monat oder einen beliebigen Berichtszeitraum zu berechnen. Das hat aber nicht gut geklappt. Zum einen weil sehr kurze Zeiträume komische Wert produzieren und ich auch bei Reihen immer Abweichungen zum Gesamtwert hatte (also z.B. wenn ich den IZF für die 12 Monate und dann für das ganze Jahr berechnet habe). Ich denke annualisierte Werte des TTWROR reichen dann für die Vergleichbarkeit.

**Comment by Beluk** [comment]
Die Beiden sind zwei unterschiedliche Betrachtungsweisen. Kurz zusammengefasst:

Der TTWROR ist die zeitgewichtete Performance, sozusagen wie gut läuft das Portfolio bei einer Einmalanlage!

Der IZF ist die kapitalgewichtete Performance und spiegelt wieder wie gut oder schlecht das Timing war.

Somit wäre es sehr schön die kapitalgewichtete Performance tagegenau zu berechnen und diese auch im Diagramm abbilden zu können. Mit dem IZF ist das aber Aufgrund der bekannten Probleme (Möglichkeit kein Ergebnis bzw. mehreren Nullstellen) fast unmöglich diese zu berechnen. 
Deshalb wäre es sinnvoll die kapitalgewichtete Performance mit der Modified Dietz Methode zu berechnen. Diese ist meiner Ansicht nach die beste Näherung und die Werte weichen meistens auch nur sehr gering ab. Der große Vorteil ist, dass diese einfach berechnet werden kann (ohne Iteration) und somit immer ein Ergebnis vorliegt.

**Comment by buchen** [comment]
> Deshalb wäre es sinnvoll die kapitalgewuchtete Performance mit der Modified Dietz Methode zu berechnen.

Absolut. Bisher wollte ich das Programm nicht unbedingt mit Zahlen überladen - aber bei guten Anwendungen.

Diesen Issue würde ich mal offen lassen und für die Annualisierung vom TTWROR verwenden.

**Comment by metal450** [comment]
From Google Translate, I *believe* this issue is a request for annualized TTWROR?  If so, I'd just like to express my interest.

Similarly to the confusion expressed in the forum [here](https://forum.portfolio-performance.info/t/annualized-ttwror/7064), when first getting started with the software I was a quite confused by - & spent some time trying to decipher - why IRR seemed to always provide expected/rational numbers, but TTWROR provided high values that didn't seem to make sense.  Eventually, I figured out why: especially when comparing with IRR, it seems like TTWROR only really makes much sense if you select a period of exactly one year.
