### ISSUE TITLE
download.finance.yahoo.com has been discontinued

### ISSUE THREAD

**Issue by tobias-kuendig** [buchen/portfolio#929]
When adding a new quote to a portfolio a 403 error is returned:

See https://download.finance.yahoo.com/d/quotes.csv?s=test&f=snl1

> It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by Ragas13** [comment]
Dear Tobias,

which version of PP did you are using? 0.28.4?

Because in November 2017 discontinued Yahoo their realtime quote download service. See also https://forum.portfolio-performance.info/t/yahoo-mit-fehler-999-yahoo-hat-api-fuer-aktuelle-kurse-abgeschaltet/1704

Beside I do not use the live stock value (only the latest closing) I could not identify at which function in PP you're struggling? Because even adding new security via Yahoo working fine for me.

Br
Marco

**Comment by tobias-kuendig** [comment]
Hi Marco

I'm on Version 0.28.4 (Linux, 64 bit)

It looks like it only happens with certain queries:
I was searching for [`IE00B88DZ566`](https://download.finance.yahoo.com/d/quotes.csv?s=IE00B88DZ566&f=snl1):

If I search for `iShares` results are returned correctly.

![image](https://user-images.githubusercontent.com/8600029/34597539-23dd0f1c-f1df-11e7-8c61-60822b063d80.png)

**Comment by megabugman** [comment]
I confirm the issue. Some assets cannot be found:
![not_found](https://user-images.githubusercontent.com/17204819/34609028-4b162d3e-f21b-11e7-897d-7bf8d4642d9b.png)
search for ticker: 
![found](https://user-images.githubusercontent.com/17204819/34609036-57c69e10-f21b-11e7-8a17-cad252ed63c1.png)
