### ISSUE TITLE
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.common

### ISSUE THREAD

**Issue by 0xdf** [buchen/portfolio#940]
I just downloaded the application for the fist time (Mac OS X 10.13.3). After installing Java 6 from the Apple homepage as prompted, the splash screen is showing when starting the application then it crashes. Logfile attached. Thanks for any help.

[1518806576084.log](https://github.com/buchen/portfolio/files/1732452/1518806576084.log)

**Comment by buchen** [comment]
The problem is this: PP needs **Java 8**. And you have to install the *Java Development Kit*. The Runtime alone does not work (is not picked up). Download the JDK here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

See here: https://forum.portfolio-performance.info/t/installation-auf-macos-10-12-2-nicht-moeglich/345/6



Unfortunately macOS stopped shipping Java and still prompts for the very old Java 6.
